### ISSUE TITLE
Can't run repyt

### ISSUE THREAD

**Issue by duttaoindril** [di/repyt#2]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\Scripts\repyt-script.py", line 11, in <module>
    load_entry_point('repyt==0.1.1', 'console_scripts', 'repyt')()
  File "c:\program files (x86)\python37-32\lib\site-packages\pkg_resources\__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\program files (x86)\python37-32\lib\site-packages\pkg_resources\__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "c:\program files (x86)\python37-32\lib\site-packages\pkg_resources\__init__.py", line 2346, in load
    return self.resolve()
  File "c:\program files (x86)\python37-32\lib\site-packages\pkg_resources\__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\program files (x86)\python37-32\lib\site-packages\repyt\repyt.py", line 2, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'

**Comment by di** [comment]
The `pwd` module is part of the standard library for both [Python 2](https://docs.python.org/2/library/pwd.html) and [Python 3](https://docs.python.org/3/library/pwd.html), where did you get your Python interpreter from? It seems to be missing things. 

**EDIT:** looks like you're using Windows and `pwd` is only available on Unix systems, so `repyt` is currently incompatible with Windows.

**Comment by duttaoindril** [comment]
I fixed it - I was on windows, just had to use bash, repyt works like a charm, thank you!
